---
title: "Insta Mkt 809"
output: html_document
---
```{r}
#clear working space
rm(orders,orders_products,ordert,products)

```


```{r}
library(data.table)
library(dplyr)
library(tidyr)
library(rpart)
library(rpart.plot)

```

```{r}
path <- "C:/Users/Jerod/Documents/SMC/Spring Qtr 18/Marketing/Project/"

aisles <- fread(file.path(path, "aisles.csv"))
departments <- fread(file.path(path, "departments.csv"))
orderp <- fread(file.path(path, "order_products__prior.csv"))
ordert <- fread(file.path(path, "order_products__train.csv"))
orders <- fread(file.path(path, "orders.csv"))
products <- fread(file.path(path, "products.csv"))

```

```{r}
str(aisles)
str(departments)
str(orders)
str(products)
str(orderp)
str(ordert)

```

```{r}
head(orderp)
head(products) #
head(orders)
head(departments)
head(aisles)
head(ordert)
head(orders_products)
```


```{r}
#convert data
aisles$aisle <- as.factor(aisles$aisle)
departments$department <- as.factor(departments$department)
orders$eval_set <- as.factor(orders$eval_set)
products$product_name <- as.factor(products$product_name)

ordert <- ordert %>%
  left_join(products, by = "product_id")
  
ordert <- ordert %>% 
  left_join(aisles, by = "aisle_id" ) %>%
  select(-aisle_id, -department_id)

products <- products %>% 
  inner_join(aisles, by = 'aisle') %>% inner_join(departments, by = 'department' ) %>% 
  select(-aisle_id, -department_id)
  #rm(aisles, departments)

#pullin in the user_id into the train set from the orders table
ordert$user_id <- orders$user_id[match(ordert$order_id, orders$order_id)]

orders_products <- orders %>% 
  inner_join(orderp, by = "order_id") %>% 
  left_join(products, by= "product_id")

rm(orderp)
gc()
```

```{r}

aisle_sum <- orders_products %>% 
  #left_join(products, by = "product_id") %>%
  arrange(user_id, order_number, aisle) %>%
  group_by(user_id, aisle) %>%
  mutate(aisle_time = row_number()) %>%
  ungroup() %>%
  group_by(aisle) %>%
  summarise(
    aisle_orders = n(),
    aisle_reorders = sum(reordered),
    aisle_first_orders = sum(aisle_time == 1),
    aisle_second_orders = sum(aisle_time == 2)
  )


aisle_sum$aisle_reorder_probability <- aisle_sum$aisle_second_orders / aisle_sum$aisle_first_orders
aisle_sum$aisle_reorder_times <- 1 + aisle_sum$aisle_reorders / aisle_sum$aisle_first_orders
aisle_sum$aisle_reorder_ratio <- aisle_sum$aisle_reorders / aisle_sum$aisle_orders

aisle_sum <- aisle_sum %>% select(-aisle_reorders, -aisle_first_orders, -aisle_second_orders)

#rm(products)
#gc()

```

```{r}
users <- orders %>% 
  filter(eval_set == "prior") %>%
  group_by(user_id) %>%
  summarise(
    user_orders = max(order_number),
    user_period = sum(days_since_prior_order, na.rm = T),
    user_mean_days_since_prior = mean(days_since_prior_order, na.rm = T)
  )

us <- orders_products %>% 
  group_by(user_id) %>%
  summarise(
    user_total_products = n(),
    user_reorder_ratio = sum(reordered == 1) / sum(order_number > 1),
    user_distinct_aisle = n_distinct(aisle)
  )

users <- users %>% inner_join(us)
users$user_average_basket <- users$user_total_products / users$user_orders

us <- orders %>%
  filter(eval_set != "prior") %>%
  select(user_id, order_id, eval_set,
         time_since_last_order = days_since_prior_order)

users <- users %>% inner_join(us)

rm(us)
#gc()

```

```{r}
data <- orders_products %>%
  #left_join(products, by = "product_id") %>%
  group_by(user_id, aisle) %>% 
  summarise(
    up_orders = n(),
    up_first_order = min(order_number),
    up_last_order = max(order_number),
    up_average_cart_position = mean(add_to_cart_order))

rm(orders_products, orders)

data <- data %>% 
  inner_join(aisle_sum, by = "aisle") %>%
  inner_join(users, by = "user_id")

data$ua_order_rate <- 
  data$up_orders / data$user_orders

data$ua_orders_since_last_order <- 
  data$user_orders - data$up_last_order

data$ua_order_rate_since_first_order <- 
  data$up_orders / (data$user_orders - data$up_first_order + 1)

ordert <- ordert %>% 
  #left_join(orders_products, by ="product_id") %>%
  select(order_id,product_id,add_to_cart_order,reordered,user_id,aisle)

data <- data %>% 
  select(-up_orders,-up_first_order,-up_last_order) %>%
  left_join(ordert %>% select(user_id, aisle, reordered), 
            by = c("user_id", "aisle"))

rm(ordert, aisle_sum, users)
gc()

#EXPORT data as csv
#write.csv(data, file = "insta_data.csv")

```

```{r}
#below create sample section not completed - need a sample to compare the prediction to and the test data has all NAs for the reordered flag. 

# CREATE SAMPLE SIZE FROM THE DATA
set.seed(2020)
dcnt_users <- reorder_dataset %>% select (user_id) %>% distinct(user_id)
train_size <- floor(0.5 * nrow(dcnt_users))
train_ind <- sample(seq_len(nrow(dcnt_users)), size = train_size) 
insta_train <- filter(reorder_dataset, user_id %in% train_ind)  


train <- as.data.frame(data[data$eval_set == "train",])

# Creation of a table with the order_ids and the products that were reordered
real_reorders <- train %>%
 filter(reordered == 1) %>%
 group_by(order_id) %>%
 summarise(
   real_aisle = paste(aisle, collapse = " ")
 )

train$eval_set <- NULL
train$user_id <- NULL
train$aisle <- NULL
train$order_id <- NULL
train$reordered[is.na(train$reordered)] <- 0

test <- as.data.frame(data[data$eval_set == "test",])
test$eval_set <- NULL
test$user_id <- NULL
test$reordered <- NULL

gc()

```

```{r}
library(xgboost)

params <- list(
  "objective"           = "reg:logistic",
  "eval_metric"         = "logloss", 
  "eta"                 = 0.1, 
  "max_depth"           = 6, 
  "min_child_weight"    = 10,  
  "gamma"               = 0.70,  
  "subsample"           = 0.76,
  "colsample_bytree"    = 0.95,  
  "alpha"               = 2e-05,  
  "lambda"              = 10 
)

subtrain <- train %>% sample_frac(0.1)
X <- xgb.DMatrix(as.matrix(subtrain %>% select(-reordered)), label = subtrain$reordered)
model <- xgboost(data = X, params = params, nrounds = 80)

importance <- xgb.importance(colnames(X), model = model)
xgb.ggplot.importance(importance)

rm(X, importance, subtrain)
gc()

```

```{r}
# Apply model to train dataset
train <- .7 * as.data.frame(data[data$eval_set == "train",])
train$eval_set <- NULL
train$user_id <- NULL
train$reordered <- NULL

X <- xgb.DMatrix(as.matrix(train %>% select(-order_id, -aisle)))
train$reordered <- predict(model, X)
train$reordered <- (train$reordered > 0.21) * 1

predicted_reorders <- train %>%
  filter(reordered == 1) %>%
  group_by(order_id) %>%
  summarise(
    predicted_aisle = paste(aisle, collapse = " ")
  )

comparison_table <- real_reorders %>% 
  inner_join(predicted_reorders, by = "order_id") 
comparison_table


#########################################################################################################
# Now apply model to test dataset

X <- xgb.DMatrix(as.matrix(test %>% select(-order_id, -product_id)))

test$reordered <- predict(model, X)

test$reordered <- (test$reordered > 0.21) * 1

submission <- test %>%
  filter(reordered == 1) %>%
  group_by(order_id) %>%
  summarise(
    products = paste(product_id, collapse = " ")
  )


missing <- data.frame(
  order_id = unique(test$order_id[!test$order_id %in% submission$order_id]),
  products = "None"
)


submission <- submission %>% bind_rows(missing) %>% arrange(order_id)
write.csv(submission, file = "submit.csv", row.names = F)

```

```{r}

library("rpart")
library("rpart.plot")
library("gains")

insta.ct <- rpart(reordered ~ ., data=train, method="class", control=rpart.control(minbucket = 15,maxsurrogate = 0))

#insta.ct <- rpart(reorder_flag ~ ., data=insta_train.agg.dedup, method="class", control=rpart.control(minbucket = 15,maxsurrogate = 0))

#prp(insta.ct)
rpart.plot(insta.ct,type=2,digits = 3, fallen.leaves = TRUE)
insta.ct

insta.prd <- predict(insta.ct, test)
head(insta.prd)

```

